* infotheo

** Installation

   The preferred way to install infotheo is with opam because it takes
   care of the dependencies with other libraries. If not already done,
   add the repository for Coq libraries to opam and update:

1. ~opam repo add coq-released https://coq.inria.fr/opam/released~
2. ~opam update~

*** Last stable version:

Version 0.0.4:
3. ~opam install coq-infotheo~

**** Requirements

- [[https://coq.inria.fr][Coq]] 8.9.1
- [[https://github.com/math-comp/math-comp][Mathematical Components library]] 1.9.0
- [[https://github.com/math-comp/analysis][MathComp-Analysis]] 0.2.2
  which requires
  + [[https://github.com/math-comp/bigenough/][bigenough]] first release
  + [[https://github.com/math-comp/finmap][finmap]] 1.2.1

All versions available from opam.

*** Development version (git master):

[[https://travis-ci.com/affeldt-aist/infotheo][file:https://travis-ci.com/affeldt-aist/infotheo.svg?branch=master]]

With Coq 8.10.

3. ~git clone git@github.com:affeldt-aist/infotheo.git~
4. ~cd infotheo~

If opam is installed, do:

5. ~opam install .~

If opam is not installed but if the requirements are met, do:

5. ~coq_makefile -f _CoqProject -o Makefile~
6. ~make~
7. ~make install~

*** About Windows 10

The installation instructions are less simple for Windows 10;
these [[https://github.com/affeldt-aist/monae/blob/master/installation_windows.org][installation instructions]] from another project using infotheo explain how to install infotheo.

** License

GNU GPLv3

** Authors

See [[infotheo_authors.txt]]

** References

There are a few papers available [[https://staff.aist.go.jp/reynald.affeldt/shannon/][here]] that provide explanations and references.

